# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tandem.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tandem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctandem.proto\x12\x06tandem\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x04\n\nTandemData\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0f\x62\x65\x61m_current_in\x18\x03 \x01(\x01\x12\x18\n\x10\x62\x65\x61m_current_out\x18\x04 \x01(\x01\x12\x16\n\x0e\x63harge_current\x18\x05 \x01(\x01\x12\x0b\n\x03gvm\x18\x06 \x01(\t\x12\x1b\n\x13\x63harge_power_supply\x18\x07 \x01(\x01\x12\n\n\x02le\x18\x08 \x01(\x01\x12\n\n\x02he\x18\t \x01(\x01\x12\x0b\n\x03\x63po\x18\n \x01(\x01\x12\x15\n\rprobe_current\x18\x0b \x01(\x01\x12\x16\n\x0eprobe_position\x18\x0c \x01(\x01\x12\x15\n\rexperiment_id\x18\r \x01(\t\x12\x1a\n\x12transmission_ratio\x18\x0e \x01(\x01\x12\x1a\n\x12transmission_slope\x18\x0f \x01(\x01\x12\x1d\n\x15transmission_variance\x18\x10 \x01(\x01\x12\x17\n\x0f\x62\x65\x61m_loss_ratio\x18\x11 \x01(\x01\x12\x1e\n\x16gvm_charge_correlation\x18\x12 \x01(\x01\x12\x1c\n\x14\x63harge_current_slope\x18\x13 \x01(\x01\x12\x1f\n\x17\x63harge_current_variance\x18\x14 \x01(\x01\x12\x11\n\tgvm_slope\x18\x15 \x01(\x01\x12\x14\n\x0cgvm_variance\x18\x16 \x01(\x01\x12\x17\n\x0fstability_score\x18\x17 \x01(\x01\x32\x82\x01\n\rTandemService\x12\x37\n\x07GetData\x12\x16.google.protobuf.Empty\x1a\x12.tandem.TandemData0\x01\x12\x38\n\x08SendData\x12\x12.tandem.TandemData\x1a\x16.google.protobuf.Empty(\x01\x42\nZ\x08pkg/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tandem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010pkg/grpc'
  _globals['_TANDEMDATA']._serialized_start=87
  _globals['_TANDEMDATA']._serialized_end=655
  _globals['_TANDEMSERVICE']._serialized_start=658
  _globals['_TANDEMSERVICE']._serialized_end=788
# @@protoc_insertion_point(module_scope)
